#!/bin/bash

#backup_mc_server
# users rsync to pull the world directory from a minecraft server,
# and creates a tar.gz archive with a date stamp

set -e

server_ip=
server_user=
world_name=

echo "Switching to working directory"
cd ~/backup_workdir

echo "Pulling files and creating archive"
rsync -aH --progress $server_user@$server_ip:minecraft/$world_name ./$world_name/
tar -cvaf $(date +%F)_$world_name.tar.gz ./$world_name/

echo "Moving archive"
mv $(date +%F)_$world_name.tar.gz ~/backup_archives/

echo "Cleaning working directory"
rm -rv *
