#!/bin/bash
set -e

rsync -aH --progress --delete /run/media/$USER/Backup_Drive/DataHoard/Pictures/ $HOME/Pictures/
rsync -aH --progress --delete /run/media/$USER/Backup_Drive/DataHoard/Music/ $HOME/
