#!/bin/bash

# `up`
# Updates anything on my Ubuntu system that can be updated from a script

set -e

# Functions for multi-command operations
function update_apt_packages() {
   sudo apt update
   sudo apt full-upgrade --autoremove --purge
   sudo apt autoclean
}

# Start doing stuff here
sudo snap refresh
flatpak update
youtube-dl -U
sudo freshclam # ClamAV virus / malware database
update_apt_packages
